### ISSUE TITLE
Fifo capacity exceeded 

### ISSUE THREAD

**Issue by WafflePersonThing** [datoviz/datoviz#28]
Unsure if this is a bug or an issue with my code but I keep getting the error 
`reallocating buffer 2 to 512.0 MBreallocating buffer 2 to 1.0 GBAssertion failed: (fifo->capacity <= 256), file C:\Users\user\project\datoviz\src\fifo.c, line 44`
I tried looking around the documentation and in the source code but i couldnt figure out why my code would be causing errors: (this is written in rust using bindings)

           let app: *mut DvzApp = dvz_app(DvzBackend_DVZ_BACKEND_GLFW);
            let gpu: *mut DvzGpu = dvz_gpu_best(app);
            let canvas: *mut DvzCanvas = dvz_canvas(gpu, 1280, 1024, 0);
            dvz_canvas_clear_color(canvas, 1.0, 1.0, 1.0);
            let scene: *mut DvzScene = dvz_scene(canvas, 1, 1);
            let mut panel = dvz_scene_panel(scene, 0, 0, DvzControllerType_DVZ_CONTROLLER_AXES_2D, 0);
            let waveforms = dvz_scene_visual(panel, DvzVisualType_DVZ_VISUAL_PATH, 0);
            let waveforms2 = dvz_scene_visual(panel, DvzVisualType_DVZ_VISUAL_PATH, 0);
            let mut pos : Vec<dvec3> = Default::default();
            let mut pos2 : Vec<dvec3> = Default::default();
            let mut color : cvec4 = [0, 0, 255, 255];
            let mut color2 : cvec4 = [255, 0, 0, 255];
            let colorc : Vec<cvec4> = vec![color, color2];
            let mut count: usize = 0;
            for i32 in &WAVEFORM {
                if count >= 2000020 {
                    break;
                }
                if count % 2 == 0 {
                    pos.push([count.clone() as f64 / 88200 as f64 / 2 as f64, *i32 as f64, 0.0 as f64]);
                } else {
                    pos2.push([count.clone() as f64 / 88200 as f64 / 2 as f64, *i32 as f64 + 20000 as f64, 0.0 as f64]);
                }
                count += 1;
            }
            dvz_visual_data(
                waveforms2,
                DvzPropType_DVZ_PROP_TOPOLOGY,
                0,
                1000000 as u32,
                0 as *const c_void,
            );
            dvz_visual_data(
                waveforms,
                DvzPropType_DVZ_PROP_TOPOLOGY,
                0,
                1000000 as u32,
                0 as *const c_void,
            );
            dvz_visual_data(
                waveforms,
                DvzPropType_DVZ_PROP_POS,
                0,
                1000000 as u32,
                pos[..1000000].as_ptr() as *const c_void,
            );

            dvz_visual_data(
                waveforms,
                DvzPropType_DVZ_PROP_COLOR,
                0,
                1 as u32,
                color.as_ptr() as *const c_void,
            );

            dvz_visual_data(
                waveforms2,
                DvzPropType_DVZ_PROP_POS,
                0,
                1000000 as u32,
                pos2[..1000000].as_ptr() as *const c_void,
            );

            dvz_visual_data(
                waveforms,
                DvzPropType_DVZ_PROP_COLOR,
                0,
                1 as u32,
                color2.as_ptr() as *const c_void,
            );
            dvz_app_run(app, 0);

            dvz_app_destroy(app);

**Comment by rossant** [comment]
I don't see anything obviously wrong in the code. Is this using the latest version on main? How do you interact with your visualization? After how long does the error appear, and under what circumstances?

Note that this part of the code is being improved in the "dynamic" branch (still an early work in progress) so this issue might be automatically solved by that, hopefully.

**Comment by WafflePersonThing** [comment]
Sorry for not putting some of the more important error info in my original comment. Im on the latest version of Datoviz. Not sure what you meant by how do i interact, also the error occurs only when i try and create 2 path visuals. With one it works fine. Then whenever i have a second one it never runs properly. One strange thing that seems to reoccur is that my ram completely fills up using an abnormal amount (like 8gb) whenever i have the two paths, freezes the window(never draws anything since its basically frozen on initialization), and then a little after it fills up completely it throws that error. I have tried increasing the fifo capacity too by changing the max value and then re compiling datoviz but that doesnt work either and the same ram filling problem happens so i dont think the problem is related to the capacity. Also there is no other code relating to Datoviz or anything that would affect it in my program.

**Comment by rossant** [comment]
Would you be able to make a minimal reproducible example in C?

**Comment by WafflePersonThing** [comment]
It's practically 1 to 1 in C, and im not well versed in the language so I can't right now. For now I could describe how to recreate it in C(should be extremely simple) and if you aren't able to recreate it I will. 
Everything except the WAVEFORM, pos1, and pos2 variables and the for loop is basically the same in C.
For the WAVEFORM variable just fill a vector or array with 2000020 floating point values ranging from 1 to -1 
Then create a variable for pos1 and pos2 which should be vectors or arrays 
Then iterate through WAVEFORM and for each even index set the same index of pos1 to that float and then for the odd number do the same
