### ISSUE TITLE
Problem running examples

### ISSUE THREAD

**Issue by pauljurczak** [datoviz/datoviz#33]
I'm using Ubuntu 20.04.3 on x86_64 CPU with Intel UHD Graphics 630 GPU, i915 driver and Python 3.8.10; datoviz is installed in venv. Simple test 
```
python -c "import datoviz; datoviz.demo()"
```
runs fine, but examples from https://datoviz.org/examples/ fail with this error message:
```
python: ../src/vklite.c:3224: dvz_cmd_begin_renderpass: Assertion `(framebuffers->framebuffers[iclip] != 0)' failed.
Aborted (core dumped)
```
In both cases I see the same warning:
```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```
but I need a lower performance settings of i915 driver in order to avoid screen tearing.

**Comment by rossant** [comment]
Are you able to temporarily set up a higher performance setting to check if you still see this error message?

**Comment by pauljurczak** [comment]
Turns out it had nothing to do with this warning, but it was a problem with Wayland. I switched back to X11 and examples run fine with or without the warning, which disappears after executing:
```
sudo sysctl dev.i915.perf_stream_paranoid=0
```
