### ISSUE TITLE
feature-request : panzoom drag + key besides of drag + right click to zoom independently in X and Y

### ISSUE THREAD

**Issue by Mriv31** [datoviz/datoviz#36]
In panzoom mode, would it be possible to add a key to zoom independently in X and Y instead of right click ? It would be very helpful in order to work with a touchpad for example.

**Comment by rossant** [comment]
Could you give a specific example of how exactly you'd expect to use mouse movements, mouse buttons, and key presses for X/Y zooming?

**Comment by Mriv31** [comment]
Actually I finally implemented that myself in Python with on_key_press.
I'm using datoviz to navigate smoothly in large 1D time series (several millions of points), and apply some operations only to the visible part of the signal. 
For such an application, I want to only zoom in x by pressing up or down and have y adjusting automatically.
But again, on_key_press does the job. 
An example of my current implementation in this video : https://drive.google.com/file/d/1NUBBs6ERCrfFEBosoDudA9s3aEi-m2YR/view?usp=sharing

**Comment by rossant** [comment]
Wow, good job! Thanks for sharing!

**Comment by grahamfindlay** [comment]
Hi @Mriv31 , would you be able to share precisely your code for doing this, or describe in more detail how you went about this? Did it require leveraging the ability to get/set panel limits in data coordinates, per f314160236b24832288a1bb17ee438aaa57a58e1? If so, did you build from source, or is there a wheel available more recent than v0.1.0-alpha.1 / 5e6e55533b643b16790149fe5462874cd5e32486?

@rossant This is amazing software, thank you so much. I have been exploring ways to create a viewer for some of my very large (6+ probe, or >24h) Neuropixel recordings, especially my spike rasters. I was looking into datoviz and found your ephysviewer.py prototype, and just the raster viewer component of that alone is magical. With a Tesla V100 I can plot 10+ million spikes in a couple of seconds. 

With the default 2D panzoom controller, I find that when panning left/right through time, I often accidentally end up panning up/down. Same for zooming in/out in time, I often inadvertently zoom in/out in depth, and vice versa. Hence a desire to be able to zoom axes independently. I was thinking that it would be nice if there were a modifier key that could discard any motion along the non-principal axis of mouse movement when dragging. 

It would also be great to be able to "go to" a specific region of a point visual, e.g. t=2100s +/- 5s. For this, I was thinking that the ability to get/set panel limits might be just what I need. Any thoughts or suggestions?

**Comment by rossant** [comment]
Sorry for the delay, and thank you for the kind words. Locking an axis in the pan/zoom controller would be indeed helpful, I'll try to do it soon.

For "go to", yes I think get/set would work. Please feel free to try and report any issue!
