### ISSUE TITLE
Is Repo Still Active?

### ISSUE THREAD

**Issue by ferjif** [datoviz/datoviz#43]
Hey,
I Noticed that the last commit on this repo is for nearly three months ago. Is this library still being actively developed?
Is there a release schedule?
If there is could you announce it?

**Comment by rossant** [comment]
Hi, Datoviz is absolutely being actively developed. I'm currently experimenting with a reorganization of the code in [another repository](https://github.com/datoviz/datoviz-distributed) which is not ready for general use yet. The goal of the reorganization is to prepare the library to become a backend for the next iteration of [VisPy](https://vispy.org/) (for which we got a CZI grant until 2024).

I'll try to find the time to write a short blog post about these ideas. In the meantime, I'll also maintain the existing codebase. Once the other repository is more mature, I'll transition the existing codebase to the new one.
