### ISSUE TITLE
Full list of public headers

### ISSUE THREAD

**Issue by hmaarrfk** [datoviz/datoviz#53]
In the top level CMakeLists file, the following:

```
set_target_properties(datoviz PROPERTIES
    VERSION ${DATOVIZ_VERSION}
    SOVERSION 1
    PUBLIC_HEADER include/datoviz/datoviz.h)
```
declares that only datoviz.h is a public headers. However it seems to be a thin shim to other files located in
https://github.com/datoviz/datoviz/tree/main/include/datoviz

Can you comment if the whole directory https://github.com/datoviz/datoviz/tree/main/include/datoviz should be listed as public headers?

https://github.com/datoviz/datoviz/blob/e26dafba0bb7b9b7cee3ee0224020c90b2fd060a/CMakeLists.txt#L458

ps. I'm trying to build a package for this: https://github.com/conda-forge/staged-recipes/pull/23164 since datoviz is only alpha for now, i may decide to not publish it on conda-forge

**Comment by rossant** [comment]
In principle, not all header files are meant to be public, however making the distinction between what function should be public and what should not is not obvious unless I were to do it on a case-by-case basis? You can also have a look at [examples](https://github.com/datoviz/datoviz/blob/main/examples/standalone/standalone_scene.c) to see what functions are typically required in simple use-cases.

Great idea to build a conda package, even if it's still in alpha. Note that I've been working on a brand new version for a long time. I intend to release it in several months. The conda recipe will have to be updated but I suspect much of the work you'll be doing here will be reusable. I have little experience with building conda packages but ideally, I think I'd like to have a language-independent module (`datoviz` or `datoviz-core` or something), with just the C/C++ library, and a `pydatoviz` or `datoviz-python` package that wraps it with Cython.

**Comment by hmaarrfk** [comment]
> what should not is not obvious unless

I was going to glob the whole directory.

>  Note that I've been working on a brand new version for a long time

Is this new version the "main branch" if so, i've been targetting that.

**Comment by rossant** [comment]
> I was going to glob the whole directory.

You'll catch many functions that won't be of much use to the general user but I guess that's not really a problem

> Is this new version the "main branch" if so, i've been targetting that.

Nope [it's here](https://github.com/datoviz/datoviz-distributed/) for now but it's still in active development and not usable by anyone yet.
