### ISSUE TITLE
Pypi v0.2; import datoviz as dvz: issues on Win11

### ISSUE THREAD

**Issue by ahip88** [datoviz/datoviz#64]
Has the wheel been tested for Win11? Running the examples e.g.
import datoviz as dvz
#followed by
app = dvz.app(0)

errors with DVZ object cannot be called as a function or 'DVZ object not callable'

I'll try to compile from source with changing the class names. It appears to be a simple conflict of clashing vars but I'm not sure.

(I had no problems with v0.1)

**Comment by rossant** [comment]
It was tested successfully on Windows 10 but not Windows 11. What is your Python distribution?

The error might be a side-effect of [this line](https://github.com/datoviz/datoviz/blob/main/datoviz/__init__.py#L77) failing (the error message should definitely be improved). Can you try to comment out the try/except clauses and just keep `dvz = ctypes.cdll.LoadLibrary(LIB_PATH)`?

**Comment by ahip88** [comment]
Yes, there we go:
The line in .../datoviz/__init__.py (line 77)
`dvz = ctypes.cdll.LoadLibrary(LIB_PATH)`

 should be

`dvz = ctypes.cdll.LoadLibrary(str(LIB_PATH))`

as you suspected the try/except clause was suppressing the fact that ctypes.cdll.LoadLibrary() expects a string as an argument, but it was being passed a WindowsPath object.
(I'm on python 3.8)
Thanks!

**Comment by rossant** [comment]
Thanks for the bug report and fix, should be fixed on main now, feel free to reopen if not!
