### ISSUE TITLE
Unable to load the shared library

### ISSUE THREAD

**Issue by guidomeijer** [datoviz/datoviz#8]
I'm at the last step of the installation but unfortunately I ran into another issue. When I run the python example it gives the error
```
Traceback (most recent call last):
  File "/home/guido/Repositories/datoviz/bindings/cython/datoviz/__init__.py", line 10, in <module>
    from .pydatoviz import App, colormap
ImportError: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bindings/cython/examples/quickstart.py", line 12, in <module>
    from datoviz import canvas, run, colormap
  File "/home/guido/Repositories/datoviz/bindings/cython/datoviz/__init__.py", line 13, in <module>
    "Unable to load the shared library, make sure to run in your terminal:\n"
ImportError: Unable to load the shared library, make sure to run in your terminal:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/build`
```
I ran ```source setup-env.sh``` which is basically the command given in the error message, but when I run ```$LD_LIBRARY_PATH``` it says
```bash: :/home/guido/Repositories/datoviz/build: No such file or directory```
However, this is the correct path so I don't understand why it can't find it.

**Comment by rossant** [comment]
I think the key bit is:

```
ImportError: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end
```

First, what is your exact operating system?

**Comment by rossant** [comment]
Also, what is your Python environment?

**Comment by guidomeijer** [comment]
I'm on Ubuntu 20.04.2 LTS and use Anaconda 4.9.2 with python 3.7.9

**Comment by rossant** [comment]
Okay, I think this is the issue: https://stackoverflow.com/a/63305833/1595060

If I understand correctly, Anaconda overrides a system lib (librsvg) with its own, and the librsvg provided in Ubuntu 20.04 (used when compiling Datoviz) doesn't match the one provided by Anaconda (use when running Python). So you have to tell Python to use the system librsvg instead of the Anaconda one. The link above should provide some guidance, I'll try to find a more automated way to fix this.

**Comment by rossant** [comment]
For the record, it seems this library is one of the many dependencies brought by ffmpeg when Datoviz is compiled with ffmpeg support (ffmpeg is only used by the integrated live screencast video feature). You could also go in the CMakeLists.txt and disable compilation with ffmpeg by replacing `set(CMAKE_VERBOSE_MAKEFILE ON)` by `set(CMAKE_VERBOSE_MAKEFILE OFF)`. This will disable the screencast feature, but will also remove the broken librsvg dependency.

**Comment by guidomeijer** [comment]
Thanks! Running the python script as follows works for me:
```LD_PRELOAD=/lib/x86_64-linux-gnu/libcairo.so.2 python bindings/cython/examples/quickstart.py```

**Comment by rossant** [comment]
Great, thanks! Will update the install instructions for Anaconda users on Ubuntu.
